/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropLockForm.java
 *
 * Created on Nov 16, 2010, 9:36:51 AM
 */

package com.echoman.designer.components.echocommon;

import java.util.ArrayList;
import java.util.List;
import com.echoman.designer.components.echobasenode.EchoBaseNode;

public class PropLockForm extends javax.swing.JDialog {
    private EchoBaseNode echonode = null;

    public PropLockForm(java.awt.Frame parent, EchoBaseNode echonode) {
        super(parent, true);
        this.echonode = echonode;
        initComponents();
        chklistProp.setClickInCheckBoxOnly(true);
        fillPropertyList();
        compName.setText(echonode.getName());
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chklistProp = new com.jidesoft.swing.CheckBoxList();
        jSeparator1 = new javax.swing.JSeparator();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        chkAllNone = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(PropLockForm.class, "PropLockForm.title_1")); // NOI18N
        setIconImages(null);
        setModal(true);
        setResizable(false);

        compName.setText(org.openide.util.NbBundle.getMessage(PropLockForm.class, "PropLockForm.compName.text")); // NOI18N

        chklistProp.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(chklistProp);

        btnOk.setText(org.openide.util.NbBundle.getMessage(PropLockForm.class, "PropLockForm.btnOk.text")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText(org.openide.util.NbBundle.getMessage(PropLockForm.class, "PropLockForm.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        chkAllNone.setText(org.openide.util.NbBundle.getMessage(PropLockForm.class, "PropLockForm.chkAllNone.text")); // NOI18N
        chkAllNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllNoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(compName))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAllNone)
                        .addContainerGap(120, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(compName)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(chkAllNone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        echonode.getNodeData().clearLockedFields();
        for (Object o : chklistProp.getCheckBoxListSelectedValues()) {
            echonode.getNodeData().addLockedField(o.toString());
        }
        echonode.refreshProperties();
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void chkAllNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllNoneActionPerformed
        if (chkAllNone.isSelected()) {
            chklistProp.selectAll();
        } else {
            chklistProp.selectNone();
        }
    }//GEN-LAST:event_chkAllNoneActionPerformed

    private void fillPropertyList() {
        List props = new ArrayList();
        for (PropInfo p : echonode.getPropertiesInfo()) {
            props.add(p.getName());
        }
        chklistProp.setListData(props.toArray());
        if (!echonode.getNodeData().getLockedFields().isEmpty()) {
            chklistProp.addCheckBoxListSelectedValues(echonode.getNodeData().getLockedFields().toArray());
            if (echonode.getNodeData().getLockedFields().size() == echonode.getPropertiesInfo().size()) {
                chkAllNone.setSelected(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox chkAllNone;
    private com.jidesoft.swing.CheckBoxList chklistProp;
    private javax.swing.JLabel compName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
