/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectListForm.java
 *
 * Created on Nov 16, 2011, 11:27:03 AM
 */
package com.echoman.designer.components.echocommon;

import java.beans.PropertyEditorSupport;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

public class SelectListForm extends javax.swing.JDialog {

    private PropertyEditorSupport editor = null;
    private DefaultListModel lstModel = new DefaultListModel();
    private DeleteActionListener deleteActionListener = null;
    private boolean accepted = false;

    public interface DeleteActionListener {

        public boolean doDelete(String data);
    }

    /** Creates new form SelectListForm */
    public SelectListForm(String title, java.awt.Frame parent,
            boolean modal, PropertyEditorSupport editor,
            String[] selections) {
        super(parent, modal);
        this.editor = editor;
        this.setTitle(title);
        initComponents();
        btnDelete.setVisible(false);
        if (editor == null) {
            setList("", selections);
        } else {
            setList(editor.getAsText(), selections);
        }
        setLocationRelativeTo(null);
    }

    public SelectListForm(String title, java.awt.Frame parent,
            boolean modal, PropertyEditorSupport editor,
            String[] selections,
            DeleteActionListener customActionListener) {
        this(title, parent, modal, editor, selections);
        this.deleteActionListener = customActionListener;
        if (customActionListener != null) {
            btnDelete.setVisible(true);
        }
    }

    private void setList(String dfltValue, String[] values) {
        lst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lst.setModel(lstModel);
        String firstVal = null;
        lstModel.removeAllElements();
        for (String val : values) {
            if (firstVal == null) {
                firstVal = val;
            }
            lstModel.addElement(val);
        }
        if (lstModel.contains(dfltValue)) {
            lst.setSelectedValue(dfltValue, true);
        } else {
            if (firstVal != null) {
                lst.setSelectedValue(firstVal, true);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lst = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        lst.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lst);

        btnOk.setText(org.openide.util.NbBundle.getMessage(SelectListForm.class, "SelectListForm.btnOk.text")); // NOI18N
        btnOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText(org.openide.util.NbBundle.getMessage(SelectListForm.class, "SelectListForm.btnCancel.text")); // NOI18N
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText(org.openide.util.NbBundle.getMessage(SelectListForm.class, "SelectListForm.btnDelete.text")); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnDelete)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        int idx = lst.getSelectedIndex();
        if (idx > -1) {
            String val = lstModel.getElementAt(idx).toString();
            String oldVal = "";
            if (editor != null) {
                oldVal = editor.getAsText();
            }
            if (doAcceptValue(oldVal, val)) {
                if (editor != null) {
                    editor.setAsText(val);
                }
                accepted = true;
                setVisible(false);
                dispose();
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    public boolean isAccepted() {
        return accepted;
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed



    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (deleteActionListener != null) {
            int idx = lst.getSelectedIndex();
            if (idx > -1) {
                String val = lstModel.getElementAt(idx).toString();
                if (deleteActionListener.doDelete(val)) {
                    lstModel.removeElementAt(idx);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMouseClicked
        if (evt.getClickCount() == 2) {
            btnOk.doClick();
        }
    }//GEN-LAST:event_lstMouseClicked

    public boolean doAcceptValue(String oldValue, String newValue) {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lst;
    // End of variables declaration//GEN-END:variables
}
