/**
 *
 */
package com.echoman.designer.components.echoform;

import javax.swing.JPanel;
import com.echoman.designer.components.echocommon.JDesiWindowManager;
import org.openide.util.NbPreferences;

/**
 * 
 * @author david.morin
 */
public final class MiscPanel extends javax.swing.JPanel {

    /**
     *
     */
    public MiscPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        gridSpace = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        displayGrid = new javax.swing.JCheckBox();
        snapOn = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.jLabel2.text")); // NOI18N

        gridSpace.setText(org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.gridSpace.text")); // NOI18N

        jLabel3.setLabelFor(gridSpace);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.jLabel3.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(displayGrid, org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.displayGrid.text")); // NOI18N

        snapOn.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(snapOn, org.openide.util.NbBundle.getMessage(MiscPanel.class, "MiscPanel.snapOn.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(snapOn)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gridSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(displayGrid))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snapOn)
                    .addComponent(jLabel3)
                    .addComponent(gridSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayGrid))
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     */
    public void load() {
        gridSpace.setText(NbPreferences.forModule(MiscPanel.class).get("gridSpace", "26"));
        snapOn.setSelected(NbPreferences.forModule(MiscPanel.class).getBoolean("snapOn", true));
        displayGrid.setSelected(NbPreferences.forModule(MiscPanel.class).getBoolean("displayGrid", true));
    }

    /**
     * 
     */
    public void store() {
        NbPreferences.forModule(MiscPanel.class).putBoolean("snapOn", snapOn.isSelected());
        NbPreferences.forModule(MiscPanel.class).putBoolean("displayGrid", displayGrid.isSelected());
        NbPreferences.forModule(MiscPanel.class).put("gridSpace", gridSpace.getText());
        //Ticket #83
        if (JDesiWindowManager.getActiveDesignerPage() != null) {
            for (JPanel pnl : JDesiWindowManager.getActiveDesignerPage().getDropPanels()) {
                EchoForm dropPanel = (EchoForm) pnl;
                dropPanel.setGridSpace(Integer.valueOf(gridSpace.getText()));
            }
        }
    }

    /**
     * 
     * @return
     */
    public boolean valid() {
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox displayGrid;
    private javax.swing.JTextField gridSpace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox snapOn;
    // End of variables declaration//GEN-END:variables
}
